## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

[train、validation、test 可參考"李宏毅"大神影片](https://youtu.be/D_S6y0Jm6dQ?t=2227)

In [1]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [3]:
# y值等於1時的index
y_1_index = np.where(y==1)[0]
# y值等於0時的index
y_0_index = np.where(y==0)[0]

- test_size 一定只能小於 1 嗎？

> If float, should be between 0.0 and 1.0 and represent the proportion of the dataset to include in the test split.

> If int, represents the absolute number of test samples.

- random_state 不設置會怎麼樣呢？

> If None, the random number generator is the RandomState instance used by np.random.

> 會用np.random取代，每次抽樣結果皆不同

In [4]:
from sklearn.model_selection import train_test_split

x_train_1, x_test_1, y_train_1, y_test_1 = train_test_split(X[y_1_index], y[y_1_index], test_size=10)

x_train_0, x_test_0, y_train_0, y_test_0 = train_test_split(X[y_0_index], y[y_0_index], test_size=10)

In [5]:
y_test = np.concatenate([y_test_1, y_test_0])
y_test

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [6]:
# 其他依此類推......
x_test = np.concatenate([x_test_1, x_test_0])
x_test

array([[190, 191, 192, 193, 194],
       [ 15,  16,  17,  18,  19],
       [130, 131, 132, 133, 134],
       [135, 136, 137, 138, 139],
       [150, 151, 152, 153, 154],
       [ 25,  26,  27,  28,  29],
       [105, 106, 107, 108, 109],
       [  5,   6,   7,   8,   9],
       [165, 166, 167, 168, 169],
       [125, 126, 127, 128, 129],
       [510, 511, 512, 513, 514],
       [795, 796, 797, 798, 799],
       [845, 846, 847, 848, 849],
       [305, 306, 307, 308, 309],
       [785, 786, 787, 788, 789],
       [800, 801, 802, 803, 804],
       [520, 521, 522, 523, 524],
       [465, 466, 467, 468, 469],
       [560, 561, 562, 563, 564],
       [565, 566, 567, 568, 569]])